# Generated by Django 4.2.20 on 2026-05-18 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('credit', models.CharField(max_length=10)),
                ('maximum_units', models.CharField(max_length=10)),
                ('long_course_title', models.TextField(blank=True, null=True)),
                ('offering_nbr', models.CharField(max_length=50)),
                ('academic_group', models.CharField(max_length=100)),
                ('subject_area', models.CharField(max_length=100)),
                ('catalog_nbr', models.CharField(max_length=50)),
                ('campus', models.CharField(max_length=100)),
                ('academic_organization', models.CharField(max_length=100)),
                ('component', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
                'db_table': 'Courses',
                'indexes': [models.Index(fields=['subject_area'], name='Courses_subject_492727_idx'), models.Index(fields=['catalog_nbr'], name='Courses_catalog_a20c2b_idx')],
            },
        ),
    ]
