# Generated by Django 4.2.20 on 2026-05-18 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
        ('attendance', '0001_initial'),
        ('lecture', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='lecture_field',
            field=models.ForeignKey(db_column='Lecture', on_delete=django.db.models.deletion.CASCADE, to='lecture.lecture'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='student',
            field=models.ForeignKey(db_column='Student', on_delete=django.db.models.deletion.CASCADE, to='students.student'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['student'], name='Attendance_Student_394afe_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['lecture_field'], name='Attendance_Lecture_3920a1_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['date'], name='Attendance_date_6d6443_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['lecture_field', 'date'], name='Attendance_Lecture_c65bf7_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['student', 'lecture_field'], name='Attendance_Student_63d3c4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('student', 'lecture_field', 'date')},
        ),
    ]
