# Generated by Django 4.2.20 on 2026-05-18 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('subject_area', models.CharField(db_index=True, max_length=100)),
                ('catalog_nbr', models.CharField(db_index=True, max_length=50)),
                ('academic_career', models.CharField(max_length=50)),
                ('offering_nbr', models.CharField(max_length=50)),
                ('start_time', models.TimeField(db_index=True)),
                ('end_time', models.TimeField(db_index=True)),
                ('section', models.CharField(max_length=50)),
                ('component', models.CharField(max_length=50)),
                ('campus', models.CharField(max_length=100)),
                ('course', models.ForeignKey(db_column='Course', on_delete=django.db.models.deletion.CASCADE, to='course.course')),
            ],
            options={
                'verbose_name': 'Lecture',
                'verbose_name_plural': 'Lectures',
                'db_table': 'Lectures',
            },
        ),
        migrations.CreateModel(
            name='LectureStudentRelation',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('day', models.CharField(db_index=True, max_length=20)),
                ('lecture_field', models.ForeignKey(db_column='Lecture', on_delete=django.db.models.deletion.CASCADE, to='lecture.lecture')),
                ('student', models.ForeignKey(db_column='Student', on_delete=django.db.models.deletion.CASCADE, to='students.student')),
            ],
            options={
                'verbose_name': 'Lecture Student Relation',
                'verbose_name_plural': 'Lecture Student Relations',
                'db_table': 'LectureStudentRelation',
            },
        ),
    ]
