# Generated by Django 4.2.20 on 2026-05-18 20:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lecture', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='instructor',
            field=models.ForeignKey(db_column='Instructor', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='lecturestudentrelation',
            index=models.Index(fields=['student'], name='LectureStud_Student_a09680_idx'),
        ),
        migrations.AddIndex(
            model_name='lecturestudentrelation',
            index=models.Index(fields=['lecture_field'], name='LectureStud_Lecture_37bad1_idx'),
        ),
        migrations.AddIndex(
            model_name='lecturestudentrelation',
            index=models.Index(fields=['day'], name='LectureStud_day_4946c0_idx'),
        ),
        migrations.AddIndex(
            model_name='lecturestudentrelation',
            index=models.Index(fields=['lecture_field', 'day'], name='LectureStud_Lecture_779ee6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='lecturestudentrelation',
            unique_together={('student', 'lecture_field', 'day')},
        ),
        migrations.AddIndex(
            model_name='lecture',
            index=models.Index(fields=['course'], name='Lectures_Course_8cb591_idx'),
        ),
        migrations.AddIndex(
            model_name='lecture',
            index=models.Index(fields=['instructor'], name='Lectures_Instruc_338594_idx'),
        ),
        migrations.AddIndex(
            model_name='lecture',
            index=models.Index(fields=['subject_area', 'catalog_nbr'], name='Lectures_subject_a70cf6_idx'),
        ),
        migrations.AddIndex(
            model_name='lecture',
            index=models.Index(fields=['start_time', 'end_time'], name='Lectures_start_t_84e564_idx'),
        ),
    ]
