# Generated by Django 4.2.20 on 2026-05-18 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('first_name', models.CharField(db_index=True, max_length=255)),
                ('middle_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(db_index=True, max_length=255)),
                ('gender', models.CharField(db_index=True, max_length=10)),
                ('face_id', models.TextField(blank=True, null=True)),
                ('create_date', models.DateField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
                'db_table': 'Students',
                'indexes': [models.Index(fields=['first_name', 'last_name'], name='Students_first_n_6616f3_idx'), models.Index(fields=['gender'], name='Students_gender_f6675e_idx'), models.Index(fields=['create_date'], name='Students_create__ef3e47_idx')],
            },
        ),
    ]
