# Generated by Django 4.2.20 on 2026-02-01 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('time', models.TimeField(db_index=True)),
                ('date', models.DateField(db_index=True)),
            ],
            options={
                'verbose_name': 'Attendance',
                'verbose_name_plural': 'Attendance Records',
                'db_table': 'Attendance',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('credit', models.CharField(max_length=10)),
                ('maximum_units', models.CharField(max_length=10)),
                ('long_course_title', models.TextField(blank=True, null=True)),
                ('offering_nbr', models.CharField(max_length=50)),
                ('academic_group', models.CharField(max_length=100)),
                ('subject_area', models.CharField(max_length=100)),
                ('catalog_nbr', models.CharField(max_length=50)),
                ('campus', models.CharField(max_length=100)),
                ('academic_organization', models.CharField(max_length=100)),
                ('component', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
                'db_table': 'Courses',
            },
        ),
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('subject_area', models.CharField(db_index=True, max_length=100)),
                ('catalog_nbr', models.CharField(db_index=True, max_length=50)),
                ('academic_career', models.CharField(max_length=50)),
                ('offering_nbr', models.CharField(max_length=50)),
                ('start_time', models.TimeField(db_index=True)),
                ('end_time', models.TimeField(db_index=True)),
                ('section', models.CharField(max_length=50)),
                ('component', models.CharField(max_length=50)),
                ('campus', models.CharField(max_length=100)),
                ('course', models.ForeignKey(db_column='Course', on_delete=django.db.models.deletion.CASCADE, to='Admin.course')),
            ],
            options={
                'verbose_name': 'Lecture',
                'verbose_name_plural': 'Lectures',
                'db_table': 'Lectures',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('role', models.CharField(db_index=True, max_length=50)),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'Users',
                'indexes': [models.Index(fields=['email'], name='Users_email_838c41_idx'), models.Index(fields=['role'], name='Users_role_e18dc1_idx')],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('first_name', models.CharField(db_index=True, max_length=255)),
                ('middle_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(db_index=True, max_length=255)),
                ('gender', models.CharField(db_index=True, max_length=10)),
                ('face_id', models.TextField(blank=True, null=True)),
                ('create_date', models.DateField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
                'db_table': 'Students',
                'indexes': [models.Index(fields=['first_name', 'last_name'], name='Students_first_n_6616f3_idx'), models.Index(fields=['gender'], name='Students_gender_f6675e_idx'), models.Index(fields=['create_date'], name='Students_create__ef3e47_idx')],
            },
        ),
        migrations.CreateModel(
            name='LectureStudentRelation',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('day', models.CharField(db_index=True, max_length=20)),
                ('lecture_field', models.ForeignKey(db_column='Lecture', on_delete=django.db.models.deletion.CASCADE, to='Admin.lecture')),
                ('student', models.ForeignKey(db_column='Student', on_delete=django.db.models.deletion.CASCADE, to='Admin.student')),
            ],
            options={
                'verbose_name': 'Lecture Student Relation',
                'verbose_name_plural': 'Lecture Student Relations',
                'db_table': 'LectureStudentRelation',
            },
        ),
        migrations.AddField(
            model_name='lecture',
            name='instructor',
            field=models.ForeignKey(db_column='Instructor', on_delete=django.db.models.deletion.CASCADE, to='Admin.user'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['subject_area'], name='Courses_subject_492727_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['catalog_nbr'], name='Courses_catalog_a20c2b_idx'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='lecture_field',
            field=models.ForeignKey(db_column='Lecture', on_delete=django.db.models.deletion.CASCADE, to='Admin.lecture'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='student',
            field=models.ForeignKey(db_column='Student', on_delete=django.db.models.deletion.CASCADE, to='Admin.student'),
        ),
        migrations.AddIndex(
            model_name='lecturestudentrelation',
            index=models.Index(fields=['student'], name='LectureStud_Student_a09680_idx'),
        ),
        migrations.AddIndex(
            model_name='lecturestudentrelation',
            index=models.Index(fields=['lecture_field'], name='LectureStud_Lecture_37bad1_idx'),
        ),
        migrations.AddIndex(
            model_name='lecturestudentrelation',
            index=models.Index(fields=['day'], name='LectureStud_day_4946c0_idx'),
        ),
        migrations.AddIndex(
            model_name='lecturestudentrelation',
            index=models.Index(fields=['lecture_field', 'day'], name='LectureStud_Lecture_779ee6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='lecturestudentrelation',
            unique_together={('student', 'lecture_field', 'day')},
        ),
        migrations.AddIndex(
            model_name='lecture',
            index=models.Index(fields=['course'], name='Lectures_Course_8cb591_idx'),
        ),
        migrations.AddIndex(
            model_name='lecture',
            index=models.Index(fields=['instructor'], name='Lectures_Instruc_338594_idx'),
        ),
        migrations.AddIndex(
            model_name='lecture',
            index=models.Index(fields=['subject_area', 'catalog_nbr'], name='Lectures_subject_a70cf6_idx'),
        ),
        migrations.AddIndex(
            model_name='lecture',
            index=models.Index(fields=['start_time', 'end_time'], name='Lectures_start_t_84e564_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['student'], name='Attendance_Student_394afe_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['lecture_field'], name='Attendance_Lecture_3920a1_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['date'], name='Attendance_date_6d6443_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['lecture_field', 'date'], name='Attendance_Lecture_c65bf7_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['student', 'lecture_field'], name='Attendance_Student_63d3c4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('student', 'lecture_field', 'date')},
        ),
    ]
