# Generated by Django 4.2.20 on 2025-09-25 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('credit', models.CharField(max_length=10)),
                ('maximum_units', models.CharField(max_length=10)),
                ('long_course_title', models.TextField(blank=True, null=True)),
                ('offering_nbr', models.CharField(max_length=50)),
                ('academic_group', models.CharField(max_length=100)),
                ('subject_area', models.CharField(max_length=100)),
                ('catalog_nbr', models.CharField(max_length=50)),
                ('campus', models.CharField(max_length=100)),
                ('academic_organization', models.CharField(max_length=100)),
                ('component', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
                'db_table': 'Courses',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=255)),
                ('middle_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=10)),
                ('face_id', models.TextField(blank=True, null=True)),
                ('create_date', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
                'db_table': 'Students',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'Users',
            },
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('subject_area', models.CharField(max_length=100)),
                ('catalog_nbr', models.CharField(max_length=50)),
                ('academic_career', models.CharField(max_length=50)),
                ('offering_nbr', models.CharField(max_length=50)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('section', models.CharField(max_length=50)),
                ('component', models.CharField(max_length=50)),
                ('campus', models.CharField(max_length=100)),
                ('course', models.ForeignKey(db_column='Course', on_delete=django.db.models.deletion.CASCADE, to='Admin.course')),
                ('instructor', models.ForeignKey(db_column='Instructor', on_delete=django.db.models.deletion.CASCADE, to='Admin.user')),
            ],
            options={
                'verbose_name': 'Class',
                'verbose_name_plural': 'Classes',
                'db_table': 'Classes',
            },
        ),
        migrations.CreateModel(
            name='ClassStudentRelation',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('day', models.CharField(max_length=20)),
                ('class_field', models.ForeignKey(db_column='Class', on_delete=django.db.models.deletion.CASCADE, to='Admin.class')),
                ('student', models.ForeignKey(db_column='Student', on_delete=django.db.models.deletion.CASCADE, to='Admin.student')),
            ],
            options={
                'verbose_name': 'Class Student Relation',
                'verbose_name_plural': 'Class Student Relations',
                'db_table': 'ClassStudentRelation',
                'unique_together': {('student', 'class_field', 'day')},
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('time', models.TimeField()),
                ('date', models.DateField()),
                ('class_field', models.ForeignKey(db_column='Class', on_delete=django.db.models.deletion.CASCADE, to='Admin.class')),
                ('student', models.ForeignKey(db_column='Student', on_delete=django.db.models.deletion.CASCADE, to='Admin.student')),
            ],
            options={
                'verbose_name': 'Attendance',
                'verbose_name_plural': 'Attendance Records',
                'db_table': 'Attendance',
                'unique_together': {('student', 'class_field', 'date')},
            },
        ),
    ]
