# Generated by Django 4.2.20 on 2025-09-25 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='time',
            field=models.TimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='class',
            name='catalog_nbr',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='class',
            name='end_time',
            field=models.TimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='class',
            name='start_time',
            field=models.TimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='class',
            name='subject_area',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='classstudentrelation',
            name='day',
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='create_date',
            field=models.DateField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='first_name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='student',
            name='last_name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(db_index=True, max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['student'], name='Attendance_Student_394afe_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['class_field'], name='Attendance_Class_3712db_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['date'], name='Attendance_date_6d6443_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['class_field', 'date'], name='Attendance_Class_710030_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['student', 'class_field'], name='Attendance_Student_1ff5ae_idx'),
        ),
        migrations.AddIndex(
            model_name='class',
            index=models.Index(fields=['course'], name='Classes_Course_d0875a_idx'),
        ),
        migrations.AddIndex(
            model_name='class',
            index=models.Index(fields=['instructor'], name='Classes_Instruc_9ccef4_idx'),
        ),
        migrations.AddIndex(
            model_name='class',
            index=models.Index(fields=['subject_area', 'catalog_nbr'], name='Classes_subject_76a704_idx'),
        ),
        migrations.AddIndex(
            model_name='class',
            index=models.Index(fields=['start_time', 'end_time'], name='Classes_start_t_257153_idx'),
        ),
        migrations.AddIndex(
            model_name='classstudentrelation',
            index=models.Index(fields=['student'], name='ClassStuden_Student_3976c7_idx'),
        ),
        migrations.AddIndex(
            model_name='classstudentrelation',
            index=models.Index(fields=['class_field'], name='ClassStuden_Class_47bb59_idx'),
        ),
        migrations.AddIndex(
            model_name='classstudentrelation',
            index=models.Index(fields=['day'], name='ClassStuden_day_6db808_idx'),
        ),
        migrations.AddIndex(
            model_name='classstudentrelation',
            index=models.Index(fields=['class_field', 'day'], name='ClassStuden_Class_3548cd_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['first_name', 'last_name'], name='Students_first_n_6616f3_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['gender'], name='Students_gender_f6675e_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['create_date'], name='Students_create__ef3e47_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='Users_email_838c41_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role'], name='Users_role_e18dc1_idx'),
        ),
    ]
